apiVersion: v1
kind: Service
metadata:
  name: book-app-service
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
