apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # base64 encoded value for 'postgres'
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value for 'password'
